swagger: '2.0'
info:
  description: Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
  version: v1.19.18
  title: Fulfillment API
  contact:
    name: eBay Inc.
  license:
    name: eBay API License Agreement
    url: https://go.developer.ebay.com/api-license-agreement
host: api.ebay.com
basePath: /sell/fulfillment/v1
schemes:
  - https
paths:
  /order/{orderId}:
    get:
      tags:
        - order
      description: 'Use this call to retrieve the contents of an order based on its unique identifier, <i>orderId</i>. This value was returned in the <b> getOrders</b> call''s <b>orders.orderId</b> field when you searched for orders by creation date, modification date, or fulfillment status. Include the optional <b>fieldGroups</b> query parameter set to <code>TAX_BREAKDOWN</code> to return a breakdown of the taxes and fees. <br /><br /> The returned <b>Order</b> object contains information you c[...]'
      operationId: getOrder
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly
  /order:
    get:
      tags:
        - order
      description: 'Use this call to search for and retrieve one or more orders based on their creation date, last modification date, or fulfillment status using the <b>filter</b> parameter. You can alternatively specify a list of orders using the <b>orderIds</b> parameter. Include the optional <b>fieldGroups</b> query parameter set to <code>TAX_BREAKDOWN</code> to return a breakdown of the taxes and fees. <br /><br /> The returned <b>Order</b> objects contain information you can use to create a[...]'
      operationId: getOrders
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly
  /order/{order_id}/issue_refund:
    post:
      tags:
        - order
      summary: Issue Refund
      description: '<div class="msgbox_important"><p class="msgbox_importantInDiv" data-mc-autonum="&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;"><span class="autonumber"><span><b><span style="color: #dd1e31;" class="mcFormatColor">Important!</span></b></span></span> Due to EU &amp; UK Payments regulatory requirements, an additional security verification via Digital Signatures is required for certain API calls that are [...]'
      operationId: issueRefund
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.finances
  /order/{orderId}/shipping_fulfillment:
    get:
      tags:
        - shipping_fulfillment
      description: Use this call to retrieve the contents of all fulfillments currently defined for a specified order based on the order's unique identifier, <b>orderId</b>. This value is returned in the <b>getOrders</b> call's <b>members.orderId</b> field when you search for orders by creation date or shipment status.
      operationId: getShippingFulfillments
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly
    post:
      tags:
        - shipping_fulfillment
      description: When you group an order's line items into one or more packages, each package requires a corresponding plan for handling, addressing, and shipping; this is a <i>shipping fulfillment</i>. For each package, execute this call once to generate a shipping fulfillment associated with that package. <br /><br /> <span class="tablenote"><strong>Note:</strong> A single line item in an order can consist of multiple units of a purchased item, and one unit can consist of multiple parts or c[...]
      operationId: createShippingFulfillment
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment
  /order/{orderId}/shipping_fulfillment/{fulfillmentId}:
    get:
      tags:
        - shipping_fulfillment
      description: Use this call to retrieve the contents of a fulfillment based on its unique identifier, <b>fulfillmentId</b> (combined with the associated order's <b>orderId</b>). The <b>fulfillmentId</b> value was originally generated by the <b>createShippingFulfillment</b> call, and is returned by the <b>getShippingFulfillments</b> call in the <b>members.fulfillmentId</b> field.
      operationId: getShippingFulfillment
      security:
        - Authorization Code:
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment
            - https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly
securityDefinitions:
  Authorization Code:
    description: The security definitions for this API. Please check individual operations for applicable scopes.
    type: oauth2
    authorizationUrl: https://auth.ebay.com/oauth2/authorize
    tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
    flow: accessCode
    scopes:
      https://api.ebay.com/oauth/api_scope/sell.fulfillment: View and manage your order fulfillments
      https://api.ebay.com/oauth/api_scope/sell.finances: View and manage your payment and order information to display this information to you and allow you to initiate refunds using the third party application
      https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly: View your order fulfillments